import { randomBytes } from 'node:crypto';
import { settingsMarkup, styles } from '../ui/markup';
import { translateMarkup, type Locale } from '../core/i18n';
import { workbenchMarkup, workbenchStyles } from './workbench-view';

const theme = `
:root{--app-font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--app-foreground:#e6e7eb;--app-editor-background:#15171b;--app-sideBar-background:#15171b;--app-descriptionForeground:#959aa7;--app-widget-border:#30343e;--app-button-background:#7379ed;--app-button-foreground:#fff;--app-button-secondaryBackground:#252832;--app-button-secondaryForeground:#dde0e9;--app-input-background:#1c1f26;--app-input-foreground:#e6e7eb;--app-input-border:#30343e;--app-input-placeholderForeground:#767c8a;--app-focusBorder:#858afd;--app-textBlockQuote-background:#22252e;--app-testing-iconPassed:#7dd5b2;--app-errorForeground:#ff9caa;--app-textLink-foreground:#a1a6ff;--app-editor-font-family:ui-monospace,SFMono-Regular,monospace;color-scheme:dark}
body{height:100dvh;overflow:hidden}.app-brand{height:40px;border-bottom:1px solid #252832;display:flex;align-items:center;justify-content:space-between;padding:0 24px;font-size:11px;letter-spacing:.6px;color:#8f95a3}.app-brand b{font-weight:600;color:#c1c6d0}.app-brand span{margin-left:12px}.chat-shell{height:calc(100dvh - 40px)!important;max-width:1050px;margin:0 auto;padding:16px 30px!important}.chat-toolbar{height:46px;font-size:14px}.chat-scroll{padding:24px 30px}.chat-welcome h1{font-size:24px}.chat-welcome p{font-size:14px}.chat-dock{padding:0 30px 18px}.chat-shell #chat-input{font-size:15px;min-height:64px}.entry-body{font-size:14px}.chat-shell .model-picker,.chat-shell .mode-select,.agent-mode{font-size:12px}.chat-shell .send-button{width:32px;height:32px}.settings-shell{height:calc(100dvh - 40px);overflow:auto;max-width:1180px}.settings-shell .hero{align-items:flex-start}.settings-shell input,.settings-shell select{min-height:42px}.settings-shell .card{background:#191c22}.settings-shell .setup-steps{display:none}.settings-nav .scope{line-height:1.8}a{color:var(--app-textLink-foreground)}
dialog{color:#e6e7eb;background:#191c22;border:1px solid #3a4050;border-radius:14px;width:min(960px,94vw);max-height:88dvh;padding:24px;box-shadow:0 24px 90px #0009}dialog::backdrop{background:#0009}.dialog-header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:16px}.dialog-header h2{margin:0}.dialog-error{color:#ff9caa;min-height:24px}.folder-list{height:35dvh;overflow:auto;margin:16px 0}.folder-list button{display:block;width:100%;text-align:left;margin:4px 0}.dialog-actions{display:flex;gap:10px;justify-content:flex-end;margin-top:14px}.preview-tabs{display:flex;gap:8px;margin:12px 0}.preview-pane{display:grid;gap:14px}.preview-pane.diff{grid-template-columns:1fr 1fr}.preview-pane pre{overflow:auto;max-height:44dvh;background:#121419;padding:16px;border:1px solid #30343e;border-radius:8px;white-space:pre-wrap;overflow-wrap:anywhere;font:12px/1.7 var(--app-editor-font-family)}.preview-label{color:#959aa7;font-size:12px;margin-top:8px}.confirm-text{white-space:pre-wrap}.server-status:empty{display:none}.server-status{color:#ffca86}.notification{position:fixed;top:50px;right:20px;z-index:10;max-width:420px;padding:14px;background:#252832;border:1px solid #3a4050;border-radius:10px}
@media(max-width:650px){.chat-shell{padding:8px 12px!important}.chat-dock,.chat-scroll{padding-left:8px;padding-right:8px}.settings-shell{padding:22px 16px}.preview-pane.diff{grid-template-columns:1fr}.app-brand{padding:0 14px}}
`;
export function browserPage(page: 'task' | 'settings', locale: Locale) {
  const nonce = randomBytes(16).toString('hex');
  const markup = translateMarkup(page === 'settings' ? settingsMarkup : workbenchMarkup, locale);
  const title = locale === 'en' ? 'FDE delivery toolkit' : 'FDE 交付工具';
  const top = translateMarkup(
    `<header class="app-brand"><div class="brand-lockup"><div class="brand-logo">✦</div><div><b>ALADDIN DIFY</b><span class="beta-label">BETA</span></div><span class="brand-description">用对话交付智能体</span></div><div class="global-controls"><span id="server-status" class="server-status" role="status"></span><button class="mobile-control" id="toggle-projects">项目</button><button class="mobile-control" id="toggle-preview">预览</button><button class="connection-control" data-command="settings"><span class="connection-led" id="connection-led"></span><span id="top-dify-address">连接 Dify</span></button><select class="top-model-select" id="top-model-select" aria-label="切换生成模型"><option value="">选择生成模型</option></select><button class="global-settings" data-command="settings" aria-label="打开全局设置">⚙ 设置</button></div></header>`,
    locale,
  );
  return `<!doctype html><html lang="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'nonce-${nonce}'; script-src 'nonce-${nonce}'; connect-src 'self'; frame-src 'self'; img-src 'self' data:; base-uri 'none'; form-action 'self';"><title>Aladdin Dify · ${title}</title><style nonce="${nonce}">${styles}${theme}${workbenchStyles}</style></head><body data-page="${page}" data-locale="${locale}">${top}${markup}<dialog id="app-dialog" aria-label="${locale === 'en' ? 'Project and review' : '项目与变更确认'}"></dialog><div id="app-notification" class="notification" hidden role="status"></div><script nonce="${nonce}" src="/browser.js"></script><script nonce="${nonce}" src="/webview.js"></script></body></html>`;
}
